In [2]:
import pandas as pd
from pathlib import Path

In [3]:
import sys

PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print(PROJECT_ROOT)

/Users/tuananhnguyen/Desktop/AI Bootcamp/Data-Analyst_HealthCare_V2

In [4]:
from app.config.paths import find_root_project

root_dir = find_root_project()

data_dir = root_dir / "data"
raw_dir = data_dir / "raw"

patients_file = raw_dir / "patients.csv"
print(root_dir)
print(patients_file)

/Users/tuananhnguyen/Desktop/AI Bootcamp/Data-Analyst_HealthCare_V2
/Users/tuananhnguyen/Desktop/AI Bootcamp/Data-Analyst_HealthCare_V2/data/raw/patients.csv

In [5]:
df_patients_data = pd.read_csv(patients_file)

In [6]:
df_patients_data.head(10)

,patient_id,patient_code,full_name,gender,date_of_birth,age,blood_type,city,district,insurance_type,chronic_condition_flag,registration_date
0,PAT000001,NVH-000001,Dang Dung,Male,1995-06-04,31,AB-,Ho Chi Minh City,Go Vap,Public Insurance,True,2023-05-28
1,PAT000002,NVH-000002,Dang Minh,Male,1948-08-18,78,A+,Can Tho,Rural Area,Corporate,False,2025-08-21
2,PAT000003,NVH-000003,Vo Son,Male,2006-02-20,20,AB+,Ho Chi Minh City,Tan Binh,Public Insurance,False,2024-02-09
3,PAT000004,NVH-000004,Ly Tri,Male,1958-06-11,68,A-,Long An,Go Vap,Self Pay,False,2024-05-08
4,PAT000005,NVH-000005,Bui Quan,Male,2002-02-12,24,A-,Dong Nai,District 1,Private Insurance,True,2025-01-17
5,PAT000006,NVH-000006,Le Tuan,Male,1994-06-15,32,A-,Ho Chi Minh City,Go Vap,Corporate,True,2025-01-29
6,PAT000007,NVH-000007,Le Phuong,Female,1961-10-02,65,O-,Ho Chi Minh City,Rural Area,Private Insurance,True,2025-02-18
7,PAT000008,NVH-000008,Ngo Nhi,Female,1947-11-03,79,O+,Ho Chi Minh City,District 7,Public Insurance,True,2023-06-26
8,PAT000009,NVH-000009,Dang Thao,Female,1986-08-24,40,O-,Vung Tau,Rural Area,Corporate,False,2023-11-21
9,PAT000010,NVH-000010,Huynh Cuong,Male,1998-10-09,28,O-,Dong Nai,District 3,Private Insurance,False,2026-04-04

In [7]:
df_patients_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4200 entries, 0 to 4199
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   patient_id              4200 non-null   str
 1   patient_code            4200 non-null   str
 2   full_name               4200 non-null   str
 3   gender                  4200 non-null   str
 4   date_of_birth           4200 non-null   str
 5   age                     4200 non-null   int64
 6   blood_type              4200 non-null   str
 7   city                    4200 non-null   str
 8   district                4200 non-null   str
 9   insurance_type          4200 non-null   str
 10  chronic_condition_flag  4200 non-null   bool
 11  registration_date       4200 non-null   str
dtypes: bool(1), int64(1), str(10)
memory usage: 736.1 KB

In [13]:
#df_patients_data["gender"].unique()
#df_patients_data["age"].min()
#df_patients_data["age"].max()
# cols = [c for c in df_patients_data.columns.tolist() if c not in ['patient_id', 'patient_code']]
# dup = df_patients_data[df_patients_data.duplicated(subset=cols)]
# dup

Empty DataFrame
Columns: [patient_id, patient_code, full_name, gender, date_of_birth, age, blood_type, city, district, insurance_type, chronic_condition_flag, registration_date]
Index: []

Xử lý :
Convert (date_of_birth, registration_date)

Dùng :
đếm số bệnh nhân đã tới bệnh viện.